name: team5-Erlang

services:
  db:
    image: mysql:8.0.40
    container_name: class_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./app/db-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3306"

  phpapp:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: php_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080:80"
    volumes:
      - ./app/php-app:/var/www/html:ro

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - ./app/node-app:/usr/src/app:ro

volumes:
  db-data:
